-- Yan Limpeza
-- Todos os objetos públicos deste sistema usam o prefixo yan_.

create schema if not exists yan_private;
revoke all on schema yan_private from public;

create table public.yan_profiles (
  user_id uuid primary key references auth.users(id) on delete cascade,
  email text not null,
  full_name text,
  role text not null default 'agent' check (role in ('admin', 'agent')),
  active boolean not null default false,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now()
);

create table yan_private.yan_bootstrap_config (
  singleton boolean primary key default true check (singleton),
  token_hash text not null,
  used_at timestamptz,
  used_by uuid references auth.users(id) on delete set null,
  created_at timestamptz not null default now()
);

-- Configure o acesso inicial diretamente no banco, por um canal privado.\n-- Não grave o hash do token de ativação em um repositório público.\n
create table public.yan_settings (
  id text primary key default 'main' check (id = 'main'),
  business_name text not null default 'Yan Limpeza',
  whatsapp text not null default '',
  city text not null default 'Indaiatuba',
  state text not null default 'SP',
  default_return_months integer not null default 6 check (default_return_months between 1 and 60),
  default_payment_days integer not null default 0 check (default_payment_days between 0 and 365),
  public_site_enabled boolean not null default true,
  updated_at timestamptz not null default now()
);

insert into public.yan_settings (id) values ('main');

create table public.yan_services (
  id uuid primary key default gen_random_uuid(),
  name text not null check (char_length(btrim(name)) between 2 and 100),
  icon text not null default 'sparkles',
  description text,
  active boolean not null default true,
  sort_order integer not null default 0,
  created_by uuid references public.yan_profiles(user_id) on delete set null,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now()
);

create unique index yan_services_name_unique on public.yan_services(lower(name));
create index yan_services_created_by_idx on public.yan_services(created_by);

create table public.yan_service_options (
  id uuid primary key default gen_random_uuid(),
  service_id uuid not null references public.yan_services(id) on delete cascade,
  name text not null check (char_length(btrim(name)) between 1 and 120),
  pricing_mode text not null default 'fixed' check (pricing_mode in ('fixed', 'per_m2', 'per_unit')),
  sale_price numeric(12,2) not null default 0 check (sale_price >= 0),
  cost_price numeric(12,2) check (cost_price is null or cost_price >= 0),
  duration_minutes integer not null default 60 check (duration_minutes between 5 and 1440),
  return_months integer not null default 6 check (return_months between 1 and 60),
  active boolean not null default true,
  sort_order integer not null default 0,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now(),
  unique (service_id, name)
);

create table public.yan_clients (
  id uuid primary key default gen_random_uuid(),
  name text not null check (char_length(btrim(name)) between 2 and 140),
  whatsapp text not null check (whatsapp ~ '^[0-9]{10,15}$'),
  email text,
  previous_customer boolean not null default false,
  last_service_date date,
  last_service_description text,
  street text,
  street_number text,
  complement text,
  neighborhood text,
  city text not null default 'Indaiatuba',
  state text not null default 'SP',
  zipcode text,
  latitude numeric(10,7),
  longitude numeric(10,7),
  decision_status text not null default 'pending' check (decision_status in ('pending', 'booked', 'not_now', 'lost')),
  follow_up_at date,
  notes text,
  created_by uuid not null default auth.uid() references public.yan_profiles(user_id) on delete restrict,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now()
);

create unique index yan_clients_whatsapp_unique on public.yan_clients(whatsapp);
create index yan_clients_decision_idx on public.yan_clients(decision_status, follow_up_at);
create index yan_clients_neighborhood_idx on public.yan_clients(neighborhood);
create index yan_clients_created_by_idx on public.yan_clients(created_by);

create table public.yan_orders (
  id uuid primary key default gen_random_uuid(),
  order_number bigint generated by default as identity unique,
  client_id uuid not null references public.yan_clients(id) on delete restrict,
  status text not null default 'draft' check (status in ('draft', 'scheduled', 'in_progress', 'completed', 'cancelled', 'refunded')),
  scheduled_start timestamptz,
  scheduled_end timestamptz,
  street text,
  street_number text,
  complement text,
  neighborhood text,
  city text,
  state text,
  subtotal numeric(12,2) not null default 0 check (subtotal >= 0),
  item_discount_total numeric(12,2) not null default 0 check (item_discount_total >= 0),
  discount_type text not null default 'fixed' check (discount_type in ('fixed', 'percent')),
  discount_value numeric(12,2) not null default 0 check (discount_value >= 0),
  discount_amount numeric(12,2) not null default 0 check (discount_amount >= 0),
  total numeric(12,2) not null default 0 check (total >= 0),
  cost_total numeric(12,2) not null default 0 check (cost_total >= 0),
  notes text,
  cancellation_reason text,
  completed_at timestamptz,
  cancelled_at timestamptz,
  created_by uuid not null default auth.uid() references public.yan_profiles(user_id) on delete restrict,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now(),
  check (scheduled_end is null or scheduled_start is null or scheduled_end > scheduled_start)
);

create index yan_orders_client_idx on public.yan_orders(client_id, created_at desc);
create index yan_orders_status_idx on public.yan_orders(status, scheduled_start);
create index yan_orders_schedule_idx on public.yan_orders(scheduled_start, scheduled_end)
  where status in ('scheduled', 'in_progress');
create index yan_orders_created_by_idx on public.yan_orders(created_by);

create table public.yan_order_items (
  id uuid primary key default gen_random_uuid(),
  order_id uuid not null references public.yan_orders(id) on delete cascade,
  service_id uuid not null references public.yan_services(id) on delete restrict,
  option_id uuid references public.yan_service_options(id) on delete set null,
  description text not null,
  pricing_mode text not null default 'fixed' check (pricing_mode in ('fixed', 'per_m2', 'per_unit')),
  quantity numeric(10,2) not null default 1 check (quantity > 0),
  unit_price numeric(12,2) not null default 0 check (unit_price >= 0),
  unit_cost numeric(12,2) not null default 0 check (unit_cost >= 0),
  discount_type text not null default 'fixed' check (discount_type in ('fixed', 'percent')),
  discount_value numeric(12,2) not null default 0 check (discount_value >= 0),
  discount_amount numeric(12,2) not null default 0 check (discount_amount >= 0),
  line_total numeric(12,2) not null default 0 check (line_total >= 0),
  duration_minutes integer not null default 60 check (duration_minutes between 5 and 1440),
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now()
);

create index yan_order_items_order_idx on public.yan_order_items(order_id);
create index yan_order_items_service_idx on public.yan_order_items(service_id);
create index yan_order_items_option_idx on public.yan_order_items(option_id);

create table public.yan_order_events (
  id uuid primary key default gen_random_uuid(),
  order_id uuid not null references public.yan_orders(id) on delete cascade,
  author_id uuid default auth.uid() references public.yan_profiles(user_id) on delete set null,
  kind text not null check (kind in ('created', 'status', 'note', 'payment', 'refund', 'schedule')),
  body text not null check (char_length(btrim(body)) between 1 and 4000),
  metadata jsonb not null default '{}'::jsonb,
  created_at timestamptz not null default now()
);

create index yan_order_events_order_idx on public.yan_order_events(order_id, created_at desc);
create index yan_order_events_author_idx on public.yan_order_events(author_id);

create table public.yan_receivables (
  id uuid primary key default gen_random_uuid(),
  order_id uuid not null references public.yan_orders(id) on delete cascade,
  installment_number integer not null check (installment_number > 0),
  amount numeric(12,2) not null check (amount > 0),
  paid_amount numeric(12,2) not null default 0 check (paid_amount >= 0),
  balance numeric(12,2) not null check (balance >= 0),
  due_date date not null,
  status text not null default 'pending' check (status in ('pending', 'partial', 'paid', 'cancelled')),
  paid_at timestamptz,
  notes text,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now(),
  unique (order_id, installment_number),
  check (paid_amount <= amount)
);

create index yan_receivables_order_idx on public.yan_receivables(order_id);
create index yan_receivables_due_idx on public.yan_receivables(status, due_date);

create table public.yan_payments (
  id uuid primary key default gen_random_uuid(),
  order_id uuid not null references public.yan_orders(id) on delete restrict,
  receivable_id uuid references public.yan_receivables(id) on delete set null,
  kind text not null default 'payment' check (kind in ('payment', 'refund')),
  amount numeric(12,2) not null check (amount > 0),
  method text not null default 'pix' check (method in ('pix', 'cash', 'card', 'transfer', 'other')),
  notes text,
  occurred_at timestamptz not null default now(),
  created_by uuid not null default auth.uid() references public.yan_profiles(user_id) on delete restrict,
  created_at timestamptz not null default now()
);

create index yan_payments_order_idx on public.yan_payments(order_id, occurred_at desc);
create index yan_payments_receivable_idx on public.yan_payments(receivable_id);
create index yan_payments_created_by_idx on public.yan_payments(created_by);

create table public.yan_follow_ups (
  id uuid primary key default gen_random_uuid(),
  client_id uuid not null references public.yan_clients(id) on delete cascade,
  service_id uuid references public.yan_services(id) on delete set null,
  source_order_id uuid references public.yan_orders(id) on delete set null,
  due_date date not null,
  kind text not null default 'manual' check (kind in ('decision', 'recurrence', 'manual')),
  status text not null default 'pending' check (status in ('pending', 'contacted', 'booked', 'snoozed', 'dismissed')),
  notes text,
  created_by uuid not null default auth.uid() references public.yan_profiles(user_id) on delete restrict,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now()
);

create index yan_follow_ups_due_idx on public.yan_follow_ups(status, due_date);
create index yan_follow_ups_client_idx on public.yan_follow_ups(client_id, due_date desc);
create index yan_follow_ups_service_idx on public.yan_follow_ups(service_id);
create index yan_follow_ups_order_idx on public.yan_follow_ups(source_order_id);
create index yan_follow_ups_created_by_idx on public.yan_follow_ups(created_by);

create or replace function yan_private.yan_set_updated_at()
returns trigger
language plpgsql
security invoker
set search_path = ''
as $$
begin
  new.updated_at = now();
  return new;
end;
$$;

create trigger yan_profiles_updated before update on public.yan_profiles
for each row execute function yan_private.yan_set_updated_at();
create trigger yan_settings_updated before update on public.yan_settings
for each row execute function yan_private.yan_set_updated_at();
create trigger yan_services_updated before update on public.yan_services
for each row execute function yan_private.yan_set_updated_at();
create trigger yan_service_options_updated before update on public.yan_service_options
for each row execute function yan_private.yan_set_updated_at();
create trigger yan_clients_updated before update on public.yan_clients
for each row execute function yan_private.yan_set_updated_at();
create trigger yan_orders_updated before update on public.yan_orders
for each row execute function yan_private.yan_set_updated_at();
create trigger yan_order_items_updated before update on public.yan_order_items
for each row execute function yan_private.yan_set_updated_at();
create trigger yan_receivables_updated before update on public.yan_receivables
for each row execute function yan_private.yan_set_updated_at();
create trigger yan_follow_ups_updated before update on public.yan_follow_ups
for each row execute function yan_private.yan_set_updated_at();

create or replace function yan_private.yan_is_active_staff()
returns boolean
language sql
stable
security definer
set search_path = ''
as $$
  select exists (
    select 1 from public.yan_profiles
    where user_id = (select auth.uid()) and active = true
  );
$$;

create or replace function yan_private.yan_is_admin()
returns boolean
language sql
stable
security definer
set search_path = ''
as $$
  select exists (
    select 1 from public.yan_profiles
    where user_id = (select auth.uid()) and active = true and role = 'admin'
  );
$$;

create or replace function public.yan_claim_access(p_bootstrap_token text default null)
returns void
language plpgsql
security definer
set search_path = ''
as $$
declare
  v_user_id uuid := auth.uid();
  v_email text;
  v_full_name text;
  v_has_profiles boolean;
  v_expected_hash text;
begin
  if v_user_id is null then raise exception 'É necessário entrar na conta.'; end if;
  if exists (select 1 from public.yan_profiles where user_id = v_user_id) then return; end if;

  perform pg_catalog.pg_advisory_xact_lock(pg_catalog.hashtextextended('yan-limpeza-bootstrap', 0));
  if exists (select 1 from public.yan_profiles where user_id = v_user_id) then return; end if;

  select u.email, nullif(btrim(coalesce(u.raw_user_meta_data ->> 'full_name', '')), '')
  into v_email, v_full_name
  from auth.users u where u.id = v_user_id;

  if v_email is null then raise exception 'Não foi possível identificar o e-mail.'; end if;
  select exists (select 1 from public.yan_profiles) into v_has_profiles;

  if not v_has_profiles then
    select token_hash into v_expected_hash
    from yan_private.yan_bootstrap_config
    where singleton = true and used_at is null
    for update;

    if v_expected_hash is null or p_bootstrap_token is null
      or pg_catalog.encode(extensions.digest(p_bootstrap_token, 'sha256'), 'hex') <> v_expected_hash then
      raise exception 'Chave inicial inválida.';
    end if;

    insert into public.yan_profiles (user_id, email, full_name, role, active)
    values (v_user_id, lower(v_email), v_full_name, 'admin', true);
    update yan_private.yan_bootstrap_config set used_at = now(), used_by = v_user_id where singleton = true;
  else
    insert into public.yan_profiles (user_id, email, full_name, role, active)
    values (v_user_id, lower(v_email), v_full_name, 'agent', false);
  end if;
end;
$$;

create or replace function public.yan_admin_set_profile(p_user_id uuid, p_active boolean, p_role text)
returns void
language plpgsql
security definer
set search_path = ''
as $$
declare
  v_current_role text;
  v_current_active boolean;
  v_admin_count integer;
begin
  if not yan_private.yan_is_admin() then raise exception 'Apenas administradores podem alterar a equipe.'; end if;
  if p_role not in ('admin', 'agent') then raise exception 'Perfil inválido.'; end if;

  select role, active into v_current_role, v_current_active
  from public.yan_profiles where user_id = p_user_id for update;
  if not found then raise exception 'Usuário não encontrado.'; end if;

  if v_current_role = 'admin' and v_current_active and (p_role <> 'admin' or not p_active) then
    select count(*) into v_admin_count from public.yan_profiles where role = 'admin' and active;
    if v_admin_count <= 1 then raise exception 'Mantenha ao menos um administrador ativo.'; end if;
  end if;

  update public.yan_profiles set active = p_active, role = p_role where user_id = p_user_id;
end;
$$;

create or replace function yan_private.yan_prepare_order_item()
returns trigger
language plpgsql
security invoker
set search_path = ''
as $$
declare
  v_gross numeric;
begin
  v_gross := round(new.quantity * new.unit_price, 2);
  new.discount_amount := case
    when new.discount_type = 'percent' then least(v_gross, round(v_gross * new.discount_value / 100, 2))
    else least(v_gross, round(new.discount_value, 2))
  end;
  new.line_total := greatest(0, v_gross - new.discount_amount);
  return new;
end;
$$;

create trigger yan_order_item_calculate
before insert or update of quantity, unit_price, unit_cost, discount_type, discount_value
on public.yan_order_items for each row execute function yan_private.yan_prepare_order_item();

create or replace function yan_private.yan_recalculate_order()
returns trigger
language plpgsql
security definer
set search_path = ''
as $$
declare
  v_order_id uuid := coalesce(new.order_id, old.order_id);
  v_subtotal numeric;
  v_after_items numeric;
  v_item_discount numeric;
  v_cost numeric;
  v_type text;
  v_value numeric;
  v_order_discount numeric;
begin
  select coalesce(sum(round(quantity * unit_price, 2)), 0),
         coalesce(sum(line_total), 0),
         coalesce(sum(discount_amount), 0),
         coalesce(sum(round(quantity * unit_cost, 2)), 0)
  into v_subtotal, v_after_items, v_item_discount, v_cost
  from public.yan_order_items where order_id = v_order_id;

  select discount_type, discount_value into v_type, v_value
  from public.yan_orders where id = v_order_id;

  v_order_discount := case
    when v_type = 'percent' then least(v_after_items, round(v_after_items * v_value / 100, 2))
    else least(v_after_items, round(v_value, 2))
  end;

  update public.yan_orders
  set subtotal = v_subtotal,
      item_discount_total = v_item_discount,
      discount_amount = v_order_discount,
      total = greatest(0, v_after_items - v_order_discount),
      cost_total = v_cost
  where id = v_order_id;
  return null;
end;
$$;

create trigger yan_order_item_recalculate
after insert or update or delete on public.yan_order_items
for each row execute function yan_private.yan_recalculate_order();

create or replace function yan_private.yan_recalculate_order_discount()
returns trigger
language plpgsql
security definer
set search_path = ''
as $$
declare
  v_after_items numeric;
begin
  select coalesce(sum(line_total), 0) into v_after_items
  from public.yan_order_items where order_id = new.id;
  new.discount_amount := case
    when new.discount_type = 'percent' then least(v_after_items, round(v_after_items * new.discount_value / 100, 2))
    else least(v_after_items, round(new.discount_value, 2))
  end;
  new.total := greatest(0, v_after_items - new.discount_amount);
  return new;
end;
$$;

create trigger yan_order_discount_calculate
before update of discount_type, discount_value on public.yan_orders
for each row execute function yan_private.yan_recalculate_order_discount();

create or replace function public.yan_check_conflicts(
  p_start timestamptz,
  p_end timestamptz,
  p_exclude_order_id uuid default null
)
returns table(order_id uuid, order_number bigint, client_name text, scheduled_start timestamptz, scheduled_end timestamptz)
language plpgsql
security definer
set search_path = ''
as $$
begin
  if not yan_private.yan_is_active_staff() then raise exception 'Acesso não autorizado.'; end if;
  return query
  select o.id, o.order_number, c.name, o.scheduled_start, o.scheduled_end
  from public.yan_orders o
  join public.yan_clients c on c.id = o.client_id
  where o.status in ('scheduled', 'in_progress')
    and o.scheduled_start < p_end
    and o.scheduled_end > p_start
    and (p_exclude_order_id is null or o.id <> p_exclude_order_id)
  order by o.scheduled_start;
end;
$$;

create or replace function public.yan_complete_order(
  p_order_id uuid,
  p_payment_mode text,
  p_installments integer default 1,
  p_first_due_date date default current_date,
  p_method text default 'pix'
)
returns void
language plpgsql
security definer
set search_path = ''
as $$
declare
  v_order public.yan_orders%rowtype;
  v_total_cents bigint;
  v_base_cents bigint;
  v_remainder bigint;
  v_piece_cents bigint;
  v_index integer;
  v_receivable_id uuid;
begin
  if not yan_private.yan_is_active_staff() then raise exception 'Acesso não autorizado.'; end if;
  if p_payment_mode not in ('paid', 'due', 'installments') then raise exception 'Forma de pagamento inválida.'; end if;
  if p_installments not between 1 and 36 then raise exception 'Informe de 1 a 36 parcelas.'; end if;
  if p_method not in ('pix', 'cash', 'card', 'transfer', 'other') then raise exception 'Meio de pagamento inválido.'; end if;

  select * into v_order from public.yan_orders where id = p_order_id for update;
  if not found then raise exception 'Ordem não encontrada.'; end if;
  if v_order.status in ('completed', 'cancelled', 'refunded') then raise exception 'Esta ordem não pode ser encerrada novamente.'; end if;
  if v_order.total <= 0 then raise exception 'A ordem precisa ter ao menos um serviço com valor.'; end if;

  update public.yan_orders
  set status = 'completed', completed_at = now()
  where id = p_order_id;

  update public.yan_clients
  set previous_customer = true,
      last_service_date = current_date,
      last_service_description = (
        select string_agg(distinct s.name, ', ' order by s.name)
        from public.yan_order_items i join public.yan_services s on s.id = i.service_id
        where i.order_id = p_order_id
      ),
      decision_status = 'booked',
      follow_up_at = null
  where id = v_order.client_id;

  v_total_cents := round(v_order.total * 100)::bigint;
  if p_payment_mode = 'paid' then
    insert into public.yan_receivables (
      order_id, installment_number, amount, paid_amount, balance, due_date, status, paid_at
    ) values (
      p_order_id, 1, v_order.total, v_order.total, 0, current_date, 'paid', now()
    ) returning id into v_receivable_id;

    insert into public.yan_payments (order_id, receivable_id, kind, amount, method, created_by)
    values (p_order_id, v_receivable_id, 'payment', v_order.total, p_method, auth.uid());
  else
    if p_payment_mode = 'due' then p_installments := 1; end if;
    v_base_cents := v_total_cents / p_installments;
    v_remainder := v_total_cents % p_installments;
    for v_index in 1..p_installments loop
      v_piece_cents := v_base_cents + case when v_index <= v_remainder then 1 else 0 end;
      insert into public.yan_receivables (
        order_id, installment_number, amount, paid_amount, balance, due_date, status
      ) values (
        p_order_id,
        v_index,
        v_piece_cents::numeric / 100,
        0,
        v_piece_cents::numeric / 100,
        (p_first_due_date + make_interval(months => v_index - 1))::date,
        'pending'
      );
    end loop;
  end if;

  insert into public.yan_follow_ups (client_id, service_id, source_order_id, due_date, kind, status, notes, created_by)
  select
    v_order.client_id,
    service_rollup.service_id,
    p_order_id,
    (current_date + make_interval(months => service_rollup.return_months))::date,
    'recurrence',
    'pending',
    'Retorno recomendado para ' || service_rollup.service_name,
    auth.uid()
  from (
    select i.service_id, s.name as service_name, min(coalesce(o.return_months, 6)) as return_months
    from public.yan_order_items i
    join public.yan_services s on s.id = i.service_id
    left join public.yan_service_options o on o.id = i.option_id
    where i.order_id = p_order_id
    group by i.service_id, s.name
  ) service_rollup;

  update public.yan_follow_ups
  set status = 'booked'
  where client_id = v_order.client_id and status in ('pending', 'contacted', 'snoozed')
    and kind = 'decision';

  insert into public.yan_order_events (order_id, author_id, kind, body, metadata)
  values (p_order_id, auth.uid(), 'status', 'Serviço concluído.', jsonb_build_object('payment_mode', p_payment_mode));
end;
$$;

create or replace function public.yan_receive_payment(
  p_receivable_id uuid,
  p_amount numeric,
  p_method text,
  p_next_due_date date default null,
  p_notes text default null
)
returns void
language plpgsql
security definer
set search_path = ''
as $$
declare
  v_receivable public.yan_receivables%rowtype;
  v_new_paid numeric;
  v_new_balance numeric;
begin
  if not yan_private.yan_is_active_staff() then raise exception 'Acesso não autorizado.'; end if;
  if p_amount is null or p_amount <= 0 then raise exception 'Informe um valor maior que zero.'; end if;
  if p_method not in ('pix', 'cash', 'card', 'transfer', 'other') then raise exception 'Meio de pagamento inválido.'; end if;

  select * into v_receivable from public.yan_receivables where id = p_receivable_id for update;
  if not found then raise exception 'Conta não encontrada.'; end if;
  if v_receivable.status in ('paid', 'cancelled') then raise exception 'Esta conta não aceita novos recebimentos.'; end if;
  if p_amount > v_receivable.balance then raise exception 'O valor informado é maior que o saldo.'; end if;

  v_new_paid := v_receivable.paid_amount + p_amount;
  v_new_balance := v_receivable.amount - v_new_paid;

  update public.yan_receivables
  set paid_amount = v_new_paid,
      balance = v_new_balance,
      due_date = case when v_new_balance > 0 and p_next_due_date is not null then p_next_due_date else due_date end,
      status = case when v_new_balance = 0 then 'paid' else 'partial' end,
      paid_at = case when v_new_balance = 0 then now() else null end,
      notes = coalesce(nullif(btrim(coalesce(p_notes, '')), ''), notes)
  where id = p_receivable_id;

  insert into public.yan_payments (order_id, receivable_id, kind, amount, method, notes, created_by)
  values (v_receivable.order_id, p_receivable_id, 'payment', p_amount, p_method, nullif(btrim(coalesce(p_notes, '')), ''), auth.uid());

  insert into public.yan_order_events (order_id, author_id, kind, body, metadata)
  values (
    v_receivable.order_id,
    auth.uid(),
    'payment',
    'Recebimento de ' || to_char(p_amount, 'FM999G999G990D00') || ' registrado.',
    jsonb_build_object('amount', p_amount, 'method', p_method)
  );
end;
$$;

create or replace function public.yan_cancel_order(p_order_id uuid, p_reason text)
returns void
language plpgsql
security definer
set search_path = ''
as $$
begin
  if not yan_private.yan_is_active_staff() then raise exception 'Acesso não autorizado.'; end if;
  if coalesce(char_length(btrim(p_reason)), 0) < 3 then raise exception 'Informe o motivo do cancelamento.'; end if;

  update public.yan_orders
  set status = 'cancelled', cancellation_reason = btrim(p_reason), cancelled_at = now()
  where id = p_order_id and status not in ('cancelled', 'refunded');
  if not found then raise exception 'Ordem não encontrada ou já cancelada.'; end if;

  update public.yan_receivables set status = 'cancelled'
  where order_id = p_order_id and status in ('pending', 'partial');

  insert into public.yan_order_events (order_id, author_id, kind, body)
  values (p_order_id, auth.uid(), 'status', 'Ordem cancelada: ' || btrim(p_reason));
end;
$$;

create or replace function public.yan_refund_order(
  p_order_id uuid,
  p_amount numeric,
  p_method text,
  p_notes text default null
)
returns void
language plpgsql
security definer
set search_path = ''
as $$
declare
  v_received numeric;
  v_refunded numeric;
begin
  if not yan_private.yan_is_active_staff() then raise exception 'Acesso não autorizado.'; end if;
  if p_amount is null or p_amount <= 0 then raise exception 'Informe o valor do estorno.'; end if;
  if p_method not in ('pix', 'cash', 'card', 'transfer', 'other') then raise exception 'Meio de estorno inválido.'; end if;

  perform 1 from public.yan_orders where id = p_order_id for update;
  if not found then raise exception 'Ordem não encontrada.'; end if;

  select coalesce(sum(amount) filter (where kind = 'payment'), 0),
         coalesce(sum(amount) filter (where kind = 'refund'), 0)
  into v_received, v_refunded
  from public.yan_payments where order_id = p_order_id;

  if p_amount > v_received - v_refunded then raise exception 'O estorno é maior que o valor recebido disponível.'; end if;

  insert into public.yan_payments (order_id, kind, amount, method, notes, created_by)
  values (p_order_id, 'refund', p_amount, p_method, nullif(btrim(coalesce(p_notes, '')), ''), auth.uid());

  if p_amount = v_received - v_refunded then
    update public.yan_orders set status = 'refunded' where id = p_order_id;
  end if;

  insert into public.yan_order_events (order_id, author_id, kind, body, metadata)
  values (
    p_order_id,
    auth.uid(),
    'refund',
    'Estorno de ' || to_char(p_amount, 'FM999G999G990D00') || ' registrado.',
    jsonb_build_object('amount', p_amount, 'method', p_method)
  );
end;
$$;

alter table public.yan_profiles enable row level security;
alter table public.yan_settings enable row level security;
alter table public.yan_services enable row level security;
alter table public.yan_service_options enable row level security;
alter table public.yan_clients enable row level security;
alter table public.yan_orders enable row level security;
alter table public.yan_order_items enable row level security;
alter table public.yan_order_events enable row level security;
alter table public.yan_receivables enable row level security;
alter table public.yan_payments enable row level security;
alter table public.yan_follow_ups enable row level security;

create policy yan_profiles_select on public.yan_profiles for select to authenticated
using (user_id = (select auth.uid()) or (select yan_private.yan_is_active_staff()));

create policy yan_settings_staff on public.yan_settings for select to authenticated
using ((select yan_private.yan_is_active_staff()));
create policy yan_settings_admin_update on public.yan_settings for update to authenticated
using ((select yan_private.yan_is_admin())) with check ((select yan_private.yan_is_admin()));

create policy yan_services_staff_select on public.yan_services for select to authenticated
using ((select yan_private.yan_is_active_staff()));
create policy yan_services_staff_insert on public.yan_services for insert to authenticated
with check ((select yan_private.yan_is_active_staff()));
create policy yan_services_staff_update on public.yan_services for update to authenticated
using ((select yan_private.yan_is_active_staff())) with check ((select yan_private.yan_is_active_staff()));
create policy yan_services_admin_delete on public.yan_services for delete to authenticated
using ((select yan_private.yan_is_admin()));

create policy yan_options_staff_select on public.yan_service_options for select to authenticated
using ((select yan_private.yan_is_active_staff()));
create policy yan_options_staff_insert on public.yan_service_options for insert to authenticated
with check ((select yan_private.yan_is_active_staff()));
create policy yan_options_staff_update on public.yan_service_options for update to authenticated
using ((select yan_private.yan_is_active_staff())) with check ((select yan_private.yan_is_active_staff()));
create policy yan_options_admin_delete on public.yan_service_options for delete to authenticated
using ((select yan_private.yan_is_admin()));

create policy yan_clients_staff_select on public.yan_clients for select to authenticated
using ((select yan_private.yan_is_active_staff()));
create policy yan_clients_staff_insert on public.yan_clients for insert to authenticated
with check ((select yan_private.yan_is_active_staff()) and created_by = (select auth.uid()));
create policy yan_clients_staff_update on public.yan_clients for update to authenticated
using ((select yan_private.yan_is_active_staff())) with check ((select yan_private.yan_is_active_staff()));
create policy yan_clients_admin_delete on public.yan_clients for delete to authenticated
using ((select yan_private.yan_is_admin()));

create policy yan_orders_staff_select on public.yan_orders for select to authenticated
using ((select yan_private.yan_is_active_staff()));
create policy yan_orders_staff_insert on public.yan_orders for insert to authenticated
with check ((select yan_private.yan_is_active_staff()) and created_by = (select auth.uid()));
create policy yan_orders_staff_update on public.yan_orders for update to authenticated
using ((select yan_private.yan_is_active_staff())) with check ((select yan_private.yan_is_active_staff()));

create policy yan_items_staff_select on public.yan_order_items for select to authenticated
using ((select yan_private.yan_is_active_staff()));
create policy yan_items_staff_insert on public.yan_order_items for insert to authenticated
with check ((select yan_private.yan_is_active_staff()));
create policy yan_items_staff_update on public.yan_order_items for update to authenticated
using ((select yan_private.yan_is_active_staff())) with check ((select yan_private.yan_is_active_staff()));
create policy yan_items_staff_delete on public.yan_order_items for delete to authenticated
using ((select yan_private.yan_is_active_staff()));

create policy yan_events_staff_select on public.yan_order_events for select to authenticated
using ((select yan_private.yan_is_active_staff()));
create policy yan_events_staff_insert on public.yan_order_events for insert to authenticated
with check ((select yan_private.yan_is_active_staff()) and author_id = (select auth.uid()));

create policy yan_receivables_staff_select on public.yan_receivables for select to authenticated
using ((select yan_private.yan_is_active_staff()));
create policy yan_payments_staff_select on public.yan_payments for select to authenticated
using ((select yan_private.yan_is_active_staff()));

create policy yan_followups_staff_select on public.yan_follow_ups for select to authenticated
using ((select yan_private.yan_is_active_staff()));
create policy yan_followups_staff_insert on public.yan_follow_ups for insert to authenticated
with check ((select yan_private.yan_is_active_staff()) and created_by = (select auth.uid()));
create policy yan_followups_staff_update on public.yan_follow_ups for update to authenticated
using ((select yan_private.yan_is_active_staff())) with check ((select yan_private.yan_is_active_staff()));
create policy yan_followups_staff_delete on public.yan_follow_ups for delete to authenticated
using ((select yan_private.yan_is_active_staff()));

revoke all on public.yan_profiles, public.yan_settings, public.yan_services,
  public.yan_service_options, public.yan_clients, public.yan_orders,
  public.yan_order_items, public.yan_order_events, public.yan_receivables,
  public.yan_payments, public.yan_follow_ups from public, anon, authenticated;
revoke all on sequence public.yan_orders_order_number_seq from public, anon, authenticated;

grant select on public.yan_profiles to authenticated;
grant select, update on public.yan_settings to authenticated;
grant select, insert, update, delete on public.yan_services, public.yan_service_options to authenticated;
grant select, insert, update, delete on public.yan_clients to authenticated;
grant select, insert, update on public.yan_orders to authenticated;
grant select, insert, update, delete on public.yan_order_items to authenticated;
grant select, insert on public.yan_order_events to authenticated;
grant select on public.yan_receivables, public.yan_payments to authenticated;
grant select, insert, update, delete on public.yan_follow_ups to authenticated;
grant usage, select on sequence public.yan_orders_order_number_seq to authenticated;

grant usage on schema yan_private to authenticated;
create index yan_bootstrap_config_used_by_idx on yan_private.yan_bootstrap_config(used_by);

revoke all on function yan_private.yan_is_active_staff() from public, anon;
revoke all on function yan_private.yan_is_admin() from public, anon;
revoke all on function yan_private.yan_set_updated_at() from public, anon, authenticated;
revoke all on function yan_private.yan_prepare_order_item() from public, anon, authenticated;
revoke all on function yan_private.yan_recalculate_order() from public, anon, authenticated;
revoke all on function yan_private.yan_recalculate_order_discount() from public, anon, authenticated;
grant execute on function yan_private.yan_is_active_staff() to authenticated;
grant execute on function yan_private.yan_is_admin() to authenticated;

revoke all on function public.yan_claim_access(text) from public, anon;
revoke all on function public.yan_admin_set_profile(uuid, boolean, text) from public, anon;
revoke all on function public.yan_check_conflicts(timestamptz, timestamptz, uuid) from public, anon;
revoke all on function public.yan_complete_order(uuid, text, integer, date, text) from public, anon;
revoke all on function public.yan_receive_payment(uuid, numeric, text, date, text) from public, anon;
revoke all on function public.yan_cancel_order(uuid, text) from public, anon;
revoke all on function public.yan_refund_order(uuid, numeric, text, text) from public, anon;

grant execute on function public.yan_claim_access(text) to authenticated;
grant execute on function public.yan_admin_set_profile(uuid, boolean, text) to authenticated;
grant execute on function public.yan_check_conflicts(timestamptz, timestamptz, uuid) to authenticated;
grant execute on function public.yan_complete_order(uuid, text, integer, date, text) to authenticated;
grant execute on function public.yan_receive_payment(uuid, numeric, text, date, text) to authenticated;
grant execute on function public.yan_cancel_order(uuid, text) to authenticated;
grant execute on function public.yan_refund_order(uuid, numeric, text, text) to authenticated;

with sofa as (
  insert into public.yan_services (name, icon, description, sort_order)
  values ('Sofá', 'sofa', 'Higienização profunda de sofás e módulos.', 1) returning id
), colchao as (
  insert into public.yan_services (name, icon, description, sort_order)
  values ('Colchão', 'bed', 'Limpeza e higienização de colchões.', 2) returning id
), cadeira as (
  insert into public.yan_services (name, icon, description, sort_order)
  values ('Cadeira', 'armchair', 'Cadeiras estofadas residenciais e comerciais.', 3) returning id
), tapete as (
  insert into public.yan_services (name, icon, description, sort_order)
  values ('Tapete', 'scan', 'Limpeza de tapetes por metragem e tipo de pelo.', 4) returning id
), poltrona as (
  insert into public.yan_services (name, icon, description, sort_order)
  values ('Poltrona', 'armchair', 'Higienização de poltronas e peças individuais.', 5) returning id
), carro as (
  insert into public.yan_services (name, icon, description, sort_order)
  values ('Banco de carro', 'car', 'Limpeza interna de bancos automotivos.', 6) returning id
), impermeabilizacao as (
  insert into public.yan_services (name, icon, description, sort_order)
  values ('Impermeabilização', 'shield', 'Proteção contra líquidos e derramamentos.', 7) returning id
)
insert into public.yan_service_options (
  service_id, name, pricing_mode, sale_price, duration_minutes, return_months, sort_order
)
select id, name, mode, price, duration, months, ordering
from (
  select id, '2 lugares'::text name, 'fixed'::text mode, 0::numeric price, 90 duration, 6 months, 1 ordering from sofa
  union all select id, '3 lugares', 'fixed', 0, 120, 6, 2 from sofa
  union all select id, 'Retrátil / reclinável', 'fixed', 0, 150, 6, 3 from sofa
  union all select id, 'Solteiro', 'fixed', 0, 60, 6, 1 from colchao
  union all select id, 'Casal', 'fixed', 0, 90, 6, 2 from colchao
  union all select id, 'Queen / King', 'fixed', 0, 120, 6, 3 from colchao
  union all select id, 'Unidade', 'per_unit', 0, 25, 6, 1 from cadeira
  union all select id, 'Sem pelo', 'per_m2', 0, 45, 6, 1 from tapete
  union all select id, 'Pelo médio', 'per_m2', 0, 60, 6, 2 from tapete
  union all select id, 'Pelo alto', 'per_m2', 0, 75, 6, 3 from tapete
  union all select id, 'Unidade', 'per_unit', 0, 60, 6, 1 from poltrona
  union all select id, 'Bancos dianteiros', 'fixed', 0, 90, 6, 1 from carro
  union all select id, 'Jogo completo', 'fixed', 0, 150, 6, 2 from carro
  union all select id, 'Por m²', 'per_m2', 0, 60, 12, 1 from impermeabilizacao
) seeded;

comment on table public.yan_clients is 'YAN: cadastro e relacionamento de clientes';
comment on table public.yan_orders is 'YAN: ordens de serviço e agenda';
comment on table public.yan_receivables is 'YAN: contas a receber';
comment on table public.yan_follow_ups is 'YAN: alertas de decisão e recorrência';
